// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWYwI_6qZIFqT8jMAg9R20KaHdfY93F40',
    appId: '1:163359601019:web:e98c036cb40a02b2e04dde',
    messagingSenderId: '163359601019',
    projectId: 'fit-flow-dev-3fd21',
    authDomain: 'fit-flow-dev-3fd21.firebaseapp.com',
    storageBucket: 'fit-flow-dev-3fd21.firebasestorage.app',
    measurementId: 'G-LNLMSBWESF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBinhcUI4qpRBGHCK51aPlBCW0JoS3_1hc',
    appId: '1:163359601019:android:a1203dc0ec6e2acae04dde',
    messagingSenderId: '163359601019',
    projectId: 'fit-flow-dev-3fd21',
    storageBucket: 'fit-flow-dev-3fd21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKa0V20md8auDk4p_NYG4EsQOdg5YdbeM',
    appId: '1:163359601019:ios:b35f57bdd7e6098fe04dde',
    messagingSenderId: '163359601019',
    projectId: 'fit-flow-dev-3fd21',
    storageBucket: 'fit-flow-dev-3fd21.firebasestorage.app',
    iosBundleId: 'com.example.fitFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKa0V20md8auDk4p_NYG4EsQOdg5YdbeM',
    appId: '1:163359601019:ios:b35f57bdd7e6098fe04dde',
    messagingSenderId: '163359601019',
    projectId: 'fit-flow-dev-3fd21',
    storageBucket: 'fit-flow-dev-3fd21.firebasestorage.app',
    iosBundleId: 'com.example.fitFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWYwI_6qZIFqT8jMAg9R20KaHdfY93F40',
    appId: '1:163359601019:web:e7702a2c3c234ce1e04dde',
    messagingSenderId: '163359601019',
    projectId: 'fit-flow-dev-3fd21',
    authDomain: 'fit-flow-dev-3fd21.firebaseapp.com',
    storageBucket: 'fit-flow-dev-3fd21.firebasestorage.app',
    measurementId: 'G-FSGQQ1HP08',
  );
}
